
import "./globals.css";


export const metadata = {
  title: "Todo List App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        cz-shortcut-listen="true"
data-new-gr-c-s-check-loaded="14.1215.0"
data-gr-ext-installed=""
      >
        {children}
      </body>
    </html>
  );
}
